services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: rfid_postgres
    environment:
      POSTGRES_DB: rfid_documents
      POSTGRES_USER: rfid_user
      POSTGRES_PASSWORD: rfid_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rfid_user -d rfid_documents"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis (optional - for development/testing)
  redis:
    image: redis:7-alpine
    container_name: rfid_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  default:
    name: rfid_network